[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5

[window]
opacity = 0.9

[colors.primary]
background = "#000000"
