[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5

#[general]
#import=["~/.config/alacritty/alabaster.toml"]

#[colors.primary]
#background = "#FFFFFF"

