#!/bin/bash
QT_QPA_PLATFORM=wayland \
XDG_CURRENT_DESKTOP=sway \
XDG_SESSION_DESKTOP=sway \
QT_QPA_PLATFORMTHEME=qt5ct \
QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
_JAVA_AWT_WM_NONREPARENTING=1 \
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
/usr/bin/sway -c ~/.config/sway/config
