require('config')
require('keymaps')
require('plugins')
require('plugins/lsp')
require('plugins/completion')
require('plugins/gitsigns')
require('plugins/translate')
require('plugins/treesitter')
require('plugins/colorscheme')
require('plugins/minipick')

