# Sway auto start after login
if [ -z "$WAYLAND_DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ] ; then
    exec sway
fi

# git branch in PS1
source /usr/lib/git-core/git-sh-prompt
PS1="${PS1}\[\033[01;35m\]\$(__git_ps1 '(%s) ')\[\033[00m\]"

